apps/items/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create/$', views.create, name="create"),
    url(r'^new/$', views.new, name="new"),
    url(r'^(?P<id>\d+)/update/$', views.update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', views.destroy, name="destroy"),
    url(r'^(?P<id>\d+)/remove/$', views.remove, name="remove"),
    url(r'^(?P<id>\d+)/add/$', views.add, name="add"),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<id>\d+)/$', views.show, name="show"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create/$', views.create, name="create"),
    url(r'^main/$', views.main, name="main"),
    url(r'^login/$', views.login, name="login"),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^(?P<id>\d+)/update/$', views.update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', views.delete, name="delete"),
    url(r'^(?P<id>\d+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<id>\d+)/$', views.show, name="show"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wish_items/', include('apps.items.urls', namespace="items")),
    url(r'^', include('apps.users.urls', namespace="users")),
]

apps/items/models.py
from django.db import models
from ..users.models import User

# Create your models here.

class ItemManager(models.Manager):
    def validate(self, form):
        errors = []
        if len(form['item_name']) == 0:
            errors.append('Item or Product must have a name')
        if len(form['item_name']) > 0 and len(form['item_name']) < 3:
            errors.append('Item or Product name must be at least three characters long')
        return errors

    def create_item(self, item_data):
        current_user = User.objects.get(id=item_data['user_id'])
        item = self.create(item_name=item_data['item_name'], user_added=current_user)
        item.user_wishlist.add(current_user)

    def delete_item(self, id):
        self.get(id=id).delete()

    def remove_item(self, id, user_data):
        current_user = User.objects.get(id=user_data['user_id'])
        self.get(id=id).user_wishlist.remove(current_user)

    def add_wishlist_item(self, id, user_data):
        current_user = User.objects.get(id=user_data['user_id'])
        self.get(id=id).user_wishlist.add(current_user)

class Item(models.Model):
    item_name = models.CharField(max_length=255)
    user_added = models.ForeignKey(User, related_name="added_item", on_delete=models.DO_NOTHING)
    user_wishlist = models.ManyToManyField(User, related_name="wishlist_item")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = ItemManager()

apps/users/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt

# Create your models here.

class UserManager(models.Manager):
    def validate(self, form):
        errors = []
        if len(form['name']) < 3:
            errors.append('Name must be at least three characters long')
        if len(form['name']) < 3:
            errors.append('Name must be at least three characters long')
        try:
            self.get(user_name=form['user_name'])
            errors.append('Username already taken, please choose a different one!')
        except:
            pass
        if len(form['password']) < 8:
            errors.append('Password must be at least 8 characters long')
        if form['password'] != form['password_confirm']:
            errors.append('Password confirmation must match password')
        return errors

    def create_user(self, user_data):
        pw_hash = bcrypt.hashpw(user_data['password'].encode(), bcrypt.gensalt())

        user = self.create(
            name=user_data['name'],
            user_name=user_data['user_name'],
            pw_hash=pw_hash,
            hire_date=user_data['hire_date']
        )
        return user

    def login(self, form):
        user_list = self.filter(user_name=form['user_name'])
        if len(user_list) > 0:
            user = user_list[0]
            if bcrypt.checkpw(form['password'].encode(), user.pw_hash.encode()):
                return (True, user.id)
            else:
                return (False, "Incorrect Username and Password Combination")
        else:
            return (False, "Incorrect Username and Password Combination")

class User(models.Model):
    name = models.CharField(max_length=255)
    user_name = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=500)
    hire_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/items/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Item
from ..users.models import User

# Create your views here.

def index(req):
    pass

def create(req):
    return render(req, 'items/create.html')

def update(req, id):
    pass

def destroy(req, id):
    if req.method != 'POST':
        return redirect('users:index')
    else:
        Item.objects.delete_item(id)
    return redirect('users:index')

def new(req):
    if req.method != 'POST':
        return redirect('items:create')
    errors = Item.objects.validate(req.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(req, error)
        return redirect('items:create')
    else:
        Item.objects.create_item(req.POST)
    return redirect('users:index')

def edit(req, id):
    pass

def show(req, id):
    context = {
        'item': Item.objects.get(id=id),
        'users': User.objects.filter(wishlist_item__id=id)
    }
    return render(req, 'items/show.html', context)

def remove(req, id):
    if req.method != 'POST':
        return redirect('users:index')
    else:
        Item.objects.remove_item(id, req.POST)
    return redirect('users:index')

def add(req, id):
    if req.method != 'POST':
        return redirect('users:index')
    else:
        Item.objects.add_wishlist_item(id, req.POST)
    return redirect('users:index')

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
from ..items.models import Item
# Create your views here.

def index(req):
    if 'user_id' in req.session:
        return redirect('users:dashboard')
    else:
        return redirect('users:main')

def create(req):
    if req.method != 'POST':
        return redirect('users:main')
    errors = User.objects.validate(req.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(req, error)
    else:
        user = User.objects.create_user(req.POST)
        req.session['user_id'] = user.id
    return redirect('users:index')

def update(req, id):
    pass

def delete(req, id):
    pass

def edit(req, id):
    pass

def show(req, id):
    pass

def login(req):
    if req.method != 'POST':
        return redirect('users:main')
    valid, response = User.objects.login(req.POST)
    if valid == True:
        req.session['user_id'] = response
        return redirect("users:index")
    else:
        messages.error(req, response)
    return redirect('users:index')

def logout(req):
    req.session.clear()
    return redirect("users:index")

def main(req):
    return render(req, 'users/main.html')

def dashboard(req):
    user = User.objects.get(id=req.session['user_id'])
    context = {
        'user': user,
        'wishlist_items': Item.objects.filter(user_wishlist__id=user.id).order_by("-updated_at"),
        'other_items': Item.objects.all().exclude(user_wishlist__id=user.id)
    }    
    return render(req, 'users/index.html', context)

apps/items/templates/items/create.html
{% extends '../users/layout.html' %}
{% block body %}
    <h1 class="display-4 text-center">Create a New Wish List Item</h1>
    {% if messages %}
    <hr class="my-4">
    <div class="row">
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{message.tags}} text-danger" {% endif %}>{{ message }}
                </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <hr class="my-4 mb-4">
    <div class="row justify-content-center align-items-center">
        <form action="{% url 'items:new' %}" method="post">
            {% csrf_token %}
            <label for="item_name">Item/Product</label>
            <input type="text" id="item_name" name="item_name">
            <input type="hidden" name="user_id" value="{{ request.session.user_id }}">
            <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>
{% endblock %}

apps/items/templates/items/show.html
{% extends '../users/layout.html' %}
{% block body %}
    <h1 class="display-4 text-center">{{ item.item_name }}</h1>
    <hr class="my-4">
    <h3 class="text-center mb-4">Users who added this item/product under their wish list:</h3>
    {% for user in users %}
    <h5 class="text-center font-weight-light mb-2"> {{ user.name }}</p>
    {% endfor %}
{% endblock %}

apps/users/templates/users/index.html
{% extends './layout.html' %}
{% block body %}
    <h1 class="display-4 text-center">Hello, {{ user.name }}</h1>
    <hr class="my-4">
    <h3 class="text-center mb-4">Your Wish List:</h3>
    <div class="row">
        <div class="col">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added By</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in wishlist_items %}
                    <tr>
                        <td><a href="{% url 'items:show' item.id %}">{{ item.item_name }}<a/></td>
                        <td>{{ item.user_added.name }}</td>
                        <td>{{ item.created_at }}</td>
                        <td>
                            {% if item.user_added.id == request.session.user_id %}
                            <form action="{% url 'items:destroy' item.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            {% else %}
                            <form action="{% url 'items:remove' item.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="user_id" name="user_id" value="{{ request.session.user_id }}">
                                <button type="submit" class="btn btn-danger">Remove</button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <hr class="my-4">
    <h3 class="text-center mb-4">Other Users' Wish List:</h3>
    <div class="row mb-4">
        <div class="col">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added By</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in other_items %}
                    <tr>
                        <td><a href="{% url 'items:show' item.id %}">{{ item.item_name }}</a></td>
                        <td>{{ item.user_added.name }}</td>
                        <td>{{ item.created_at }}</td>
                        <td>
                            <form action="{% url 'items:add' item.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" id="user_id" name="user_id" value="{{ request.session.user_id }}">
                                <button type="submit" class="btn btn-success">Add to My Wish List</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <hr class="my-4">
    <div class="row justify-content-center">
        <a href="{% url 'items:create' %}" class="btn btn-success">Add Item</a>
    </div>
{% endblock %}

apps/users/templates/users/layout.html
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Wish List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="container bg-light">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand text-white">Wish List</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    {% if 'user_id' in request.session %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                    </li>
                    {% endif %}
                    </ul>
                </div>
                </nav>
        <div class="jumbotron jumbotron-fluid bg-light">
            {% block body %} {% endblock %}
        </div>
    </div>
</body>
</html>

apps/users/templates/users/main.html
{% extends './layout.html' %}
{% block body %}
    <h1 class="display-4 text-center">Welcome!</h1>
    {% if messages %}
    <div class="row">
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{message.tags}}, text-danger" {% endif %}>{{ message }}
                </li>
            {% endfor %}
        </ul>
        <hr class="my-4">
    </div>
    {% endif %}
    <div class="row">
        <div class="col-6 border-right">
            <h2 class="text-center mb-5">Register</h2>
            <form action="{% url 'users:create' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-7">
                        <label for="name">Name</label>
                    </div>
                    <div class="col">
                        <input type="text" name="name" placeholder="Your Name">
                    </div>
                </div>
                <div class="form-row mb-3">
                    <div class="col-7">
                        <label for="username">Username</label>
                    </div>
                    <div class="col">
                        <input type="text" name="user_name" placeholder="Desired Username">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-7">
                        <label for="password">Password</label>
                    </div>
                    <div class="col">
                        <input type="password" name="password">
                    </div>
                </div>
                <div class="form-row mb-1">
                    <div class="col-7">
                        <label for="password_confirm">Confirm Password</label>
                    </div>
                    <div class="col">
                        <input type="password" name="password_confirm">
                    </div>
                </div>
                <div class="form-row mb-3">
                    <p class="font-weight-light">*Password must be atleast 8 characters</p>
                </div>
                <div class="form-row mb-5">
                    <div class="col-7">
                        <label for="hire_date">Date Hired</label>
                    </div>
                    <div class="col">
                        <input type="date" name="hire_date">
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <button type="submit" class="btn btn-success">Register</button>
                </div>
            </form>
        </div>
        <div class="col-6 border-left">
            <h2 class="text-center mb-5">Login</h2>
            <div class="form">
                <form action="{% url 'users:login' %}" method="post">
                    <div class="form-row mb-5">
                        {% csrf_token %}
                        <div class="col"
                            <label for="user_name">Username</label>
                            <input type="text" name="user_name">
                        </div>
                        <div class="col">
                            <label for="password">Password</label>
                            <input type="password" name="password">
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}